### ISSUE TITLE
Direction with ncurses

### ISSUE THREAD

**Issue by nickago** [nickfrostatx/gitcontrib#6]
So I wanted the have this discussion before submitting #2 but it's still very revertible. Do we want to go the ncurses route or try some other way to abstract our terminal output?

**Comment by DeltaHeavy** [comment]
I don't mind the ncurses idea, especially if we take it further in terms of maybe some interactivity (viewing file-by-file contribution, x-other-random-idea) but it should definitely ask the term for the color background so it's not a startling change to gray from say, the dark soft blue of solarized. Thoughts?

**Comment by nickago** [comment]
Alright, since that's in the readme as a todo, I'm going to say this thread has accomplished its goal
